name: Run Tests

on:
  push:

  pull_request:
    types: [opened, reopened]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v4

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Deps
        run: |
          yarn
          yarn build

      - name: Test
        run: |
          cd packages/core && yarn test

      - name: Test React Lite
        run: |
          cd packages/react-lite && yarn test
